create table public.profiles (id uuid primary key references auth.users(id) on delete cascade, email text not null, full_name text, role text not null default 'pending' check(role in ('pending','lector','muestreador','admin')), created_date timestamptz not null default now());
alter table public.profiles enable row level security;
create schema if not exists private;
create function private.has_role(roles text[]) returns boolean language sql stable security definer set search_path = '' as $$ select exists(select 1 from public.profiles where id=(select auth.uid()) and role=any(roles)); $$;
revoke all on function private.has_role(text[]) from public;
grant usage on schema private to authenticated;
grant execute on function private.has_role(text[]) to authenticated;
create policy profiles_read on public.profiles for select to authenticated using (id=(select auth.uid()) or private.has_role(array['admin']));
grant select on public.profiles to authenticated;
create function private.new_user() returns trigger language plpgsql security definer set search_path = '' as $$ begin insert into public.profiles(id,email,full_name) values(new.id,new.email,new.raw_user_meta_data->>'full_name'); return new; end; $$;
revoke all on function private.new_user() from public;
create trigger create_profile after insert on auth.users for each row execute function private.new_user();
create table public.fincas (id uuid primary key default gen_random_uuid(), created_date timestamptz not null default now(), created_by uuid not null default auth.uid() references auth.users(id), "name" text not null, "region" text, "lat" double precision, "lng" double precision);
alter table public.fincas enable row level security;
create policy read_members on public.fincas for select to authenticated using (private.has_role(array['admin','muestreador','lector']));
create policy insert_members on public.fincas for insert to authenticated with check (private.has_role(array['admin']) and created_by=(select auth.uid()));
create policy update_members on public.fincas for update to authenticated using (private.has_role(array['admin'])) with check (private.has_role(array['admin']));
create policy delete_admin on public.fincas for delete to authenticated using(private.has_role(array['admin']));
grant select,insert,update,delete on public.fincas to authenticated;
create table public.variedades (id uuid primary key default gen_random_uuid(), created_date timestamptz not null default now(), created_by uuid not null default auth.uid() references auth.users(id), "name" text not null);
alter table public.variedades enable row level security;
create policy read_members on public.variedades for select to authenticated using (private.has_role(array['admin','muestreador','lector']));
create policy insert_members on public.variedades for insert to authenticated with check (private.has_role(array['admin']) and created_by=(select auth.uid()));
create policy update_members on public.variedades for update to authenticated using (private.has_role(array['admin'])) with check (private.has_role(array['admin']));
create policy delete_admin on public.variedades for delete to authenticated using(private.has_role(array['admin']));
grant select,insert,update,delete on public.variedades to authenticated;
create table public.bloques (id uuid primary key default gen_random_uuid(), created_date timestamptz not null default now(), created_by uuid not null default auth.uid() references auth.users(id), "finca_id" uuid references public.fincas(id) on delete restrict not null, "name" text not null, "variedad_id" uuid references public.variedades(id) on delete restrict, "area_ha" double precision, "tree_count" double precision, "plant_year" double precision);
alter table public.bloques enable row level security;
create policy read_members on public.bloques for select to authenticated using (private.has_role(array['admin','muestreador','lector']));
create policy insert_members on public.bloques for insert to authenticated with check (private.has_role(array['admin']) and created_by=(select auth.uid()));
create policy update_members on public.bloques for update to authenticated using (private.has_role(array['admin'])) with check (private.has_role(array['admin']));
create policy delete_admin on public.bloques for delete to authenticated using(private.has_role(array['admin']));
grant select,insert,update,delete on public.bloques to authenticated;
create index on public.bloques("finca_id");
create index on public.bloques("variedad_id");
create table public.clases_comerciales (id uuid primary key default gen_random_uuid(), created_date timestamptz not null default now(), created_by uuid not null default auth.uid() references auth.users(id), "variedad_id" uuid references public.variedades(id) on delete restrict, "name" text not null, "min_mm" double precision not null, "max_mm" double precision not null, "order" double precision);
alter table public.clases_comerciales enable row level security;
create policy read_members on public.clases_comerciales for select to authenticated using (private.has_role(array['admin','muestreador','lector']));
create policy insert_members on public.clases_comerciales for insert to authenticated with check (private.has_role(array['admin']) and created_by=(select auth.uid()));
create policy update_members on public.clases_comerciales for update to authenticated using (private.has_role(array['admin'])) with check (private.has_role(array['admin']));
create policy delete_admin on public.clases_comerciales for delete to authenticated using(private.has_role(array['admin']));
grant select,insert,update,delete on public.clases_comerciales to authenticated;
create index on public.clases_comerciales("variedad_id");
create table public.metas_bloque (id uuid primary key default gen_random_uuid(), created_date timestamptz not null default now(), created_by uuid not null default auth.uid() references auth.users(id), "bloque_id" uuid references public.bloques(id) on delete restrict not null, "season" text, "target_date" date, "target_diameter_mm" double precision, "target_red_pct" double precision, "max_cracking_pct" double precision, "max_sunburn_pct" double precision, "max_russet_pct" double precision);
alter table public.metas_bloque enable row level security;
create policy read_members on public.metas_bloque for select to authenticated using (private.has_role(array['admin','muestreador','lector']));
create policy insert_members on public.metas_bloque for insert to authenticated with check (private.has_role(array['admin']) and created_by=(select auth.uid()));
create policy update_members on public.metas_bloque for update to authenticated using (private.has_role(array['admin'])) with check (private.has_role(array['admin']));
create policy delete_admin on public.metas_bloque for delete to authenticated using(private.has_role(array['admin']));
grant select,insert,update,delete on public.metas_bloque to authenticated;
create index on public.metas_bloque("bloque_id");
create table public.sesiones (id uuid primary key default gen_random_uuid(), created_date timestamptz not null default now(), created_by uuid not null default auth.uid() references auth.users(id), "bloque_id" uuid references public.bloques(id) on delete restrict not null, "muestreador_name" text, "started_at" timestamptz, "ended_at" timestamptz, "status" text check ("status" in ('borrador','procesando','listo','error')) default 'borrador', "photo_count" double precision default 0, "fruit_count" double precision default 0, "avg_diameter_mm" double precision, "red_pct" double precision, "cracking_pct" double precision, "sunburn_pct" double precision, "russet_pct" double precision);
alter table public.sesiones enable row level security;
create policy read_members on public.sesiones for select to authenticated using (private.has_role(array['admin','muestreador','lector']));
create policy insert_members on public.sesiones for insert to authenticated with check (private.has_role(array['admin','muestreador']) and created_by=(select auth.uid()));
create policy update_members on public.sesiones for update to authenticated using (private.has_role(array['admin','muestreador']) and (created_by=(select auth.uid()) or private.has_role(array['admin']))) with check (private.has_role(array['admin','muestreador']) and (created_by=(select auth.uid()) or private.has_role(array['admin'])));
create policy delete_admin on public.sesiones for delete to authenticated using(private.has_role(array['admin']));
grant select,insert,update,delete on public.sesiones to authenticated;
create index on public.sesiones("bloque_id");
create table public.fotos (id uuid primary key default gen_random_uuid(), created_date timestamptz not null default now(), created_by uuid not null default auth.uid() references auth.users(id), "session_id" uuid references public.sesiones(id) on delete restrict not null, "captured_at" timestamptz, "storage_uri" text, "lat" double precision, "lng" double precision, "status" text check ("status" in ('procesando','listo','error')) default 'procesando', "fruit_count_estimate" double precision, "avg_diameter_mm" double precision, "fruits" jsonb, capture_metadata jsonb, measurement_status text not null default 'unmeasured');
alter table public.fotos enable row level security;
create policy read_members on public.fotos for select to authenticated using (private.has_role(array['admin','muestreador','lector']));
create policy insert_members on public.fotos for insert to authenticated with check (private.has_role(array['admin','muestreador']) and created_by=(select auth.uid()) and exists(select 1 from public.sesiones s where s.id=session_id and (s.created_by=(select auth.uid()) or private.has_role(array['admin']))));
create policy update_members on public.fotos for update to authenticated using (private.has_role(array['admin','muestreador']) and (created_by=(select auth.uid()) or private.has_role(array['admin']))) with check (private.has_role(array['admin','muestreador']) and (created_by=(select auth.uid()) or private.has_role(array['admin'])));
create policy delete_admin on public.fotos for delete to authenticated using(private.has_role(array['admin']));
grant select,insert,update,delete on public.fotos to authenticated;
create index on public.fotos("session_id");
insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types) values('photos','photos',false,15000000,array['image/jpeg']);
create policy upload_photos on storage.objects for insert to authenticated with check (bucket_id='photos' and (storage.foldername(name))[1]=(select auth.uid())::text and private.has_role(array['admin','muestreador']));
create policy read_photos on storage.objects for select to authenticated using (bucket_id='photos' and private.has_role(array['admin','muestreador','lector']));
-- Projects with automatic API exposure disabled also require explicit server grants.
grant select,insert,update,delete on all tables in schema public to service_role;
-- Supabase may create this event-trigger function when automatic RLS is enabled.
do $$ begin
  if to_regprocedure('public.rls_auto_enable()') is not null then
    revoke all on function public.rls_auto_enable() from public,anon,authenticated;
  end if;
end $$;
